Repository EcoJulia/EcologicalNetworks.jl, pull requests merged in 2020-11, with the labels that each got.

#169 Address review comments
  README.md
  paper/fig/workflow.PNG
  paper/paper.bib
  paper/paper.md
Labels: paper

#173 Avoids returning NaN in functional roles
  Makefile
  Project.toml
  src/community/nestedness.jl
  src/community/overlap.jl
  src/community/resilience.jl
  src/information/entropy.jl
  src/links/connectance.jl
  src/links/degree.jl
  src/modularity/labelpropagation.jl
  src/modularity/roles.jl
  src/rand/sample.jl
  src/rand/shuffle.jl
  src/structuralmodels/cascademodel.jl
  src/structuralmodels/nestedhierarchymodel.jl
  src/types/iteration.jl
  src/types/utilities.jl
  test/modularity/roles.jl
Labels: bug

#172 Example use case
  docs/make.jl
  docs/src/examples/integration_mangal.md
Labels: documentation, paper

#174 add DataFrames and Plots to doc dependencies
  docs/Project.toml
Labels: documentation

#176 fix example use case
  docs/src/examples/integration_mangal.md
Labels: bug, documentation
